// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCORHW4H3oK1jtCUyIuEBSDI0O-bAkxfpM',
    appId: '1:736228801855:web:05ad2385a1441ff3b3278a',
    messagingSenderId: '736228801855',
    projectId: 'levora-44ae4',
    authDomain: 'levora-44ae4.firebaseapp.com',
    storageBucket: 'levora-44ae4.firebasestorage.app',
    measurementId: 'G-5N0VKYY71J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQag-LFD7kDx8iKcDhITUJ5L9Pul54EWs',
    appId: '1:736228801855:android:457055d826aaefc8b3278a',
    messagingSenderId: '736228801855',
    projectId: 'levora-44ae4',
    storageBucket: 'levora-44ae4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVgbKAbDfNyRXVWPlVJOV6kWxhrllE_oQ',
    appId: '1:736228801855:ios:0a17058c47c6136bb3278a',
    messagingSenderId: '736228801855',
    projectId: 'levora-44ae4',
    storageBucket: 'levora-44ae4.firebasestorage.app',
    iosClientId: '736228801855-uand4ptbhst8jt5vc53e8ei0171gh20p.apps.googleusercontent.com',
    iosBundleId: 'com.example.levora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVgbKAbDfNyRXVWPlVJOV6kWxhrllE_oQ',
    appId: '1:736228801855:ios:0a17058c47c6136bb3278a',
    messagingSenderId: '736228801855',
    projectId: 'levora-44ae4',
    storageBucket: 'levora-44ae4.firebasestorage.app',
    iosClientId: '736228801855-uand4ptbhst8jt5vc53e8ei0171gh20p.apps.googleusercontent.com',
    iosBundleId: 'com.example.levora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCORHW4H3oK1jtCUyIuEBSDI0O-bAkxfpM',
    appId: '1:736228801855:web:da9ce809afd4419db3278a',
    messagingSenderId: '736228801855',
    projectId: 'levora-44ae4',
    authDomain: 'levora-44ae4.firebaseapp.com',
    storageBucket: 'levora-44ae4.firebasestorage.app',
    measurementId: 'G-Q95ESF4XV3',
  );
}
